name: Build workflow

on: [ push ]

jobs:
  action:
    name: Action
    uses: leo-e-org/github-workflows/.github/workflows/main-build-k8s-go.yml@main
    with:
      image_name: ${{ github.repository }}
    secrets: inherit
